#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linting and formatting on pre-commit
echo "Running pre-commit checks..."
yarn lint:fix
yarn format
yarn tsc:check
yarn test
#yarn storybook:test
echo "Pre-commit checks completed."